# dev-env — papanix-ai CLIs + opt-in per-contributor dev tooling.
#
# `lib.devEnv.mk` bundles things individual contributors usually want
# in their shell but that don't belong in the core PAPA CLI set:
#
#   • Node.js (+ npm bundled, opt-in corepack for pnpm/yarn shims)
#   • Playwright (browsers prebuilt by nixpkgs; env vars wired so
#     `npx playwright` reuses them instead of downloading at runtime)
#   • Arbitrary extra packages
#
# Returns `{ packages; shellHook; }` — splice both into your devShell.
# Nothing is written to or wiped from your project tree (this is NOT
# an ephemeral feature module).
#
# No repo-local config is generated by default. Copy the MCP shell hook
# from `default/flake.nix` if you want MCP here too.
# Sandboxed `claude` is still on PATH so contributors can use it without
# extra project wiring.
{
  description = "papanix-ai: CLIs + sandboxed `claude` + opt-in per-contributor dev environment";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    papanix-ai.url = "github:fmgordillo-dyna/papanix-ai";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = {
    nixpkgs,
    flake-utils,
    papanix-ai,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (
      system: let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };

        cliPackages = with papanix-ai.packages.${system}; [
          acli-pii
          aimgr
          bbctl
          dtctl
          junoctl
        ];

        # NOTE: Customize the sandboxed `claude` wrapper here.
        sandboxedClaude = papanix-ai.lib.sandboxing.mkClaudeSandbox {
          inherit pkgs cliPackages;
          claudePkg = pkgs.claude-code;

          # NOTE: Safe defaults already include the selected PAPA CLIs plus
          # common helpers like `git`, `rg`, `fd`, `jq`, `curl`, `file`,
          # `tree`, `tar`, `zip`, `unzip`, `node`, and `nix`.
          # extraAllowedPackages = with pkgs; [ gh kubectl ];

          # NOTE: Persist extra tool state or individual config files.
          # extraRwDirs = [ "$HOME/.config/gh" "$HOME/.kube" ];
          # extraRwFiles = [ "$HOME/.kube/config" ];

          # NOTE: Bind read-only config into the sandbox when needed.
          # extraRoDirs = [ "$HOME/.config/some-readonly-tree" ];
          # extraRoFiles = [ "$HOME/.gitconfig" ];

          # NOTE: Pass extra env vars through to the sandboxed process.
          # extraEnv = {
          #   GH_TOKEN = "$GH_TOKEN";
          #   KUBECONFIG = "$HOME/.kube/config";
          # };

          restrictNetwork = false;
          # NOTE: Only used when `restrictNetwork = true;`.
          # allowedDomains = {
          #   "github.com" = [ "GET" "HEAD" ];
          #   "api.anthropic.com" = "*";
          # };

          # NOTE: Enable if Claude needs SSH remotes from inside the sandbox.
          # exposeSsh = true;
        };

        # NOTE: Toggle the bits you want. Every key is optional; omit /
        # set to `false` to leave it out.
        devEnv = papanix-ai.lib.devEnv.mk {
          inherit pkgs;

          # nodejs — `true` for defaults, or an attrset:
          #   version       — nixpkgs attr name. Default "nodejs" (LTS).
          #                   Examples: "nodejs_20", "nodejs_22", "nodejs_23".
          #   withCorepack  — adds the `corepack` package for pnpm/yarn shims.
          nodejs = {
            version = "nodejs_22";
            withCorepack = true;
          };

          # playwright — `true` for defaults (driver + browsers + env vars
          # so `npx playwright` reuses the Nix-built browser bundle), or:
          #   withBrowsers — false to skip the prebuilt browsers and manage
          #                  them yourself.
          playwright = true;

          # Verbatim list appended to the result — handy for ad-hoc
          # global tooling that doesn't have a dedicated knob.
          # extraPackages = with pkgs.nodePackages; [ typescript prettier ];
        };
      in {
        packages = papanix-ai.packages.${system};

        devShells.default = pkgs.mkShellNoCC {
          packages =
            # Selected PAPA CLIs plus sandboxed `claude`.
            (cliPackages ++ [sandboxedClaude])
            ++ devEnv.packages;

          # Playwright env vars live here.
          shellHook = devEnv.shellHook;
        };
      }
    );
}
